name: Test Python Script

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.x', 3.7, 3.8, 3.9, "3.10", 3.11, 3.12]
        exclude:
          - python-version: "3.6"
          - python-version: "3.1"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    # - name: Install dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install -r requirements.txt  # If you have any dependencies

    - name: Run Python script tests
      run: |
        python keys.py -u oliv10
        exit_code=$?

        if [ $exit_code -eq 0 ]; then
          echo "Python script test passed successfully."
        else
          echo "Python script test failed with exit code $exit_code."
          exit 1
        fi
