name: Test Bash Script

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Test Bash script
      run: |
        chmod +x script_name.sh
        ./keys.sh -u oliv10
        exit_code=$?

        if [ $exit_code -eq 0 ]; then
          echo "Bash script test passed successfully."
        else
          echo "Bash script test failed with exit code $exit_code."
          exit 1
        fi
